require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# Gemspec
Gemspec/RequireMFA:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

# RSpec
RSpec/FilePath:
  SpecSuffixOnly: true
  Enabled: true

RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/StringLiterals:
  Enabled: false