name: Publish
on:
  release:
    types: [ published ]

jobs:
  publish:
    if: github.repository == 'securionpay/securionpay-python'
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: gem build
      - run: gem push securionpay-*.*.*.gem