name: Publish
on:
  release:
    types: [ published ]

jobs:
  publish:
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: gem build
      - run: gem push securionpay-*.*.*.gem